version: '3.4'

services:
  api:
    container_name: BindyBotApi
    build:
      context: .
      dockerfile: BindyBot.API/Dockerfile
    env_file:
      - .env
      - api.env
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:15-alpine
    container_name: PostgresDb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge